/** Líneas con tokens tipo VS Code — 1 columna a ancho completo */

export const ghostCodeColumns = [
  [
    [{ type: "comment", text: "// React · API client" }],
    [
      { type: "keyword", text: "import" },
      { type: "plain", text: " { " },
      { type: "function", text: "useEffect" },
      { type: "plain", text: " } " },
      { type: "keyword", text: "from" },
      { type: "string", text: '"react"' },
    ],
    [
      { type: "keyword", text: "export" },
      { type: "plain", text: " " },
      { type: "keyword", text: "async" },
      { type: "plain", text: " " },
      { type: "keyword", text: "function" },
      { type: "function", text: "fetchData" },
      { type: "plain", text: "(url: " },
      { type: "type", text: "string" },
      { type: "plain", text: ") {" },
    ],
    [
      { type: "plain", text: "  " },
      { type: "keyword", text: "const" },
      { type: "plain", text: " res = " },
      { type: "keyword", text: "await" },
      { type: "function", text: "fetch" },
      { type: "plain", text: "(url)" },
    ],
    [
      { type: "plain", text: "  " },
      { type: "keyword", text: "return" },
      { type: "plain", text: " res." },
      { type: "function", text: "json" },
      { type: "plain", text: "()" },
    ],
    [{ type: "plain", text: "}" }],
    [{ type: "comment", text: "# Terraform · GCP" }],
    [
      { type: "function", text: "resource" },
      { type: "string", text: ' "google_cloud_run_service"' },
      { type: "string", text: ' "api"' },
      { type: "plain", text: " {" },
    ],
    [
      { type: "plain", text: "  name     = " },
      { type: "function", text: "var" },
      { type: "plain", text: ".service_name" },
    ],
    [
      { type: "plain", text: "  location = " },
      { type: "string", text: '"europe-west1"' },
    ],
    [{ type: "plain", text: "}" }],
    [{ type: "comment", text: "# CI/CD · GitHub Actions" }],
    [
      { type: "property", text: "github_actions" },
      { type: "plain", text: " {" },
    ],
    [
      { type: "plain", text: "  " },
      { type: "property", text: "branches" },
      { type: "plain", text: " = [" },
      { type: "string", text: '"main"' },
      { type: "plain", text: "]" },
    ],
    [{ type: "plain", text: "}" }],
    [{ type: "comment", text: "--- Astro layout ---" }],
    [
      { type: "keyword", text: "import" },
      { type: "plain", text: " Layout " },
      { type: "keyword", text: "from" },
      { type: "string", text: '"../layouts/Layout.astro"' },
    ],
    [
      { type: "keyword", text: "const" },
      { type: "plain", text: " { title } = Astro.props" },
    ],
    [{ type: "comment", text: "<Layout title={title}>" }],
    [
      { type: "plain", text: "  <" },
      { type: "type", text: "HeroSection" },
      { type: "plain", text: " client:load />" },
    ],
    [{ type: "comment", text: "// TypeScript" }],
    [
      { type: "keyword", text: "interface" },
      { type: "plain", text: " " },
      { type: "type", text: "Project" },
      { type: "plain", text: " {" },
    ],
    [
      { type: "plain", text: "  title: " },
      { type: "type", text: "string" },
    ],
    [
      { type: "plain", text: "  tags: " },
      { type: "type", text: "string" },
      { type: "plain", text: "[]" },
    ],
    [{ type: "plain", text: "}" }],
    [
      { type: "keyword", text: "export" },
      { type: "plain", text: " " },
      { type: "keyword", text: "const" },
      { type: "plain", text: " projects: Project[]" },
    ],
    [{ type: "comment", text: "// PHP · PrestaShop" }],
    [
      { type: "keyword", text: "namespace" },
      { type: "plain", text: " Databay\\ICEditorial" },
    ],
    [
      { type: "keyword", text: "class" },
      { type: "plain", text: " " },
      { type: "type", text: "OrderSync" },
      { type: "plain", text: " {" },
    ],
    [
      { type: "keyword", text: "public" },
      { type: "plain", text: " " },
      { type: "keyword", text: "function" },
      { type: "function", text: "handleWebhook" },
      { type: "plain", text: "(): " },
      { type: "type", text: "void" },
    ],
    [{ type: "plain", text: "{" }],
    [
      { type: "plain", text: "  $" },
      { type: "property", text: "payload" },
      { type: "plain", text: " = " },
      { type: "function", text: "json_decode" },
      { type: "plain", text: "($" },
      { type: "property", text: "input" },
      { type: "plain", text: ")" },
    ],
    [
      { type: "plain", text: "  " },
      { type: "keyword", text: "if" },
      { type: "plain", text: " (! $" },
      { type: "property", text: "payload" },
      { type: "plain", text: ") {" },
    ],
    [
      { type: "plain", text: "    " },
      { type: "keyword", text: "return" },
    ],
    [{ type: "plain", text: "  }" }],
    [{ type: "plain", text: "}" }],
    [{ type: "comment", text: "// Odoo · Verifactu" }],
    [
      { type: "property", text: "invoice" },
      { type: "plain", text: "." },
      { type: "function", text: "action_post" },
      { type: "plain", text: "()" },
    ],
  ],
];
